joint_cohort : gvcfs.tsv
species      : horse
ref          : goldenPath
date         : ''
bucket       : ''
alias        : s3
profile      : ''

# SINGULARITY IMAGE
sif : /home/fried255/cull0084/.sif/wags.sif

# CONDA ENV
conda_envs :
  qc : bcftools

# DB IMPORT
batch_size : 50

# REFERENCE FILES
ref_fasta : /home/refgen/horse/goldenPath/goldenPath.Ec_build-3.0_wMSY.fa
ref_dict  : /home/refgen/horse/goldenPath/goldenPath.Ec_build-3.0_wMSY.dict
ref_gtf   : /home/refgen/horse/goldenPath/MISSING.gtf

# TMP DIRS - NOTE THIS NEEDS TO BE BASED ON SETUP
tmp_dir :
  sites_only_gather_vcf : /scratch.global/friedlab_JOINT/.sites_gather
  unfilt_gather_vcf     : /scratch.global/friedlab_JOINT/.unfilt_gather

# RECAL
snp_recalibration_tranche_values    : [
  "100.0", "99.95", "99.9", "99.5", "99.0", "98.0", 
  "97.0", "96.0", "95.0", "94.0", "93.0", "92.0", "91.0", "90.0"]
snp_recalibration_annotation_values : ["QD", "MQRankSum", "ReadPosRankSum", "FS", "MQ", "SOR", "DP"]
snp_filter_level   : 99.0

indel_recalibration_tranche_values    : [
  "100.0", "99.95", "99.9", "99.5", "99.0", "98.0", 
  "97.0", "96.0", "95.0", "94.0", "93.0", "92.0", "91.0", "90.0"]
indel_recalibration_annotation_values : ["FS", "ReadPosRankSum", "MQRankSum", "QD", "SOR", "DP"]
indel_filter_level : 99.0

# RESOURCE FILES (FROM CONTAINER)
#k9hd_axiom_vcf : /home/refgen/dog/UU_Cfam_GSD_1.0_ROSY/resources/SRZ189891_722g.simp.header.CanineHDandAxiom_K9_HD.GSD_1.0.vcf.gz
#coverage_sites : /home/refgen/dog/UU_Cfam_GSD_1.0_ROSY/resources/SRZ189891_722g.simp.header.CanineHD.names.GSD_1.0.filter.vcf.gz

# OUTPUT OPTIONS
# PHASING
phasing  : false
link_map : /home/refgen/horse/goldenPath/MISSING.linkage.map

