# INPUT AND SECONDARY
units   : input.tsv
species : dog
ref     : canfam4
bucket  : wags
alias   : s3

# SINGULARITY IMAGE
sif : /path/to/WAGS/wags.sif

# LEFT ALIGN BAM
left_align : false

# TMP DIRS - NOTE SORT AND SITES ONLY NEEDS TO BE BASED ON PROC DIC + "sort_gather"
tmp_dir :
    sort_tmp                 : /path/to/proc/dir
    sites_only_gather_vcf    : /scratch.global/friedlab_JOINT_CF3/sort_gather
    select_variants_to_table : /dev/shm/money_vars

# BQSR INTERVAL PARAMS
contig_n_size : 50
scatter_size : 50

# CONDA ENVS
conda_envs :
    vep : ensembl-vep

# POPULATION VCF
pop_vcf : /path/to/pop.ref.vcf
#pop_vcf     : /panfs/roc/groups/0/fried255/fried255/working/pipeline/20210512/VEP/joint_genotype.canfam3.20210512.vcf.gz
#common_vars : /panfs/roc/groups/0/fried255/fried255/working/pipeline/20210512/VEP/CommonVars/joint_genotype.canfam3.vep.af_nonmajor.vcf.gz
#common_vars_tbi : /panfs/roc/groups/0/fried255/fried255/working/pipeline/20210512/VEP/CommonVars/joint_genotype.canfam3.vep.af_nonmajor.vcf.gz.tbi

# REFERENCE FILES 
ref_fasta : /home/refgen/dog/canfam4/canFam4.fa
ref_dict  : /home/refgen/dog/canfam4/canFam4.dict
ref_gtf   : /home/refgen/dog/canfam4/UU_Cfam_GSD_1.0_ROSY.refSeq.ensformat.gtf.gz

# RECAL
indel_recalibration_tranche_values    : ["100.0", "99.95", "99.9", "99.5", "99.0", "97.0", "96.0", "95.0", "94.0", "93.5", "93.0", "92.0", "91.0", "90.0"]
indel_recalibration_annotation_values : ["FS", "ReadPosRankSum", "MQRankSum", "QD", "SOR", "DP"]
snp_recalibration_tranche_values      : ["100.0", "99.95", "99.9", "99.8", "99.6", "99.5", "99.4", "99.3", "99.0", "98.0", "97.0", "90.0" ]
snp_recalibration_annotation_values   : ["QD", "MQRankSum", "ReadPosRankSum", "FS", "MQ", "SOR", "DP"]

indel_filter_level : 99.7
snp_filter_level   : 99.7

# RESOURCE FILES (FROM CONTAINER)
#known_sites :
dbsnp_indels_vcf : /home/refgen/dog/canfam4/resources/canFam4.recoded.dbsnp.151.indels.sorted.fixed.header.chr.vcf
dbsnp_snp_vcf    : /home/refgen/dog/canfam4/resources/canFam4.recoded.dbsnp.151.snps.sorted.fixed.header.chr.vcf
broad_snp_vcf    : /home/refgen/dog/canfam4/resources/canFam4.final.broad.snps.sorted.fixed.header.chr.vcf
axelsson_snp_vcf : /home/refgen/dog/canfam4/resources/canFam4.final.axelsson.snps.sorted.fixed.header.chr.vcf
illumina_snp_vcf : /home/refgen/dog/canfam4/resources/canFam4.illumina.snps.sorted.fixed.header.chr.vcf

# RANDOM PARAMS
excess_het_threshold : 54.69


# INTERVALS - NOTE GENERATE AS PART OF PIPELINE
#hc_intervals       : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/refdata/canFam3/intervals/Splint100/
#eval_interval_list : /panfs/roc/groups/0/fried255/cull0084/projects/gatk4_pipeline/intervals/acgt.N1000.interval_list
