# COMMON INPUTS
units : input.tsv
primary : /panfs/roc/groups/0/fried255/fried255/working

# INTERVALS
hc_intervals : 
    canfam3 : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/refdata/canFam3/intervals/Splint100/
    canfam4 : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/refdata/CanFam4/Intervals/Splint_NOCHRUN/
eval_interval_list :
    canfam3 : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/refdata/canFam3/intervals/acgt.N1000.interval_list
    canfam4 : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/refdata/CanFam4/Intervals/acgt_no_chrun.N50.interval_list

# COMMON TOOLS
gatk : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/tools/gatk-4.2.0.0/gatk
gatk3 : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/tools/GenomeAnalysisTK.jar
fastqc : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/tools/FastQC/fastqc
picard : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/tools/picard.jar
bwa : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/tools/bwa-0.7.17/bwa
samtools : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/tools/samtools-1.9/samtools

# VEP VERSIONS
conda_vep :
    canfam3 : vep98
    canfam4 : vep103

# POPULATION VCFS
pop_vcf :
    canfam3 : /panfs/roc/groups/0/fried255/fried255/working/pipeline/20210512/VEP/joint_genotype.canfam3.20210512.vcf.gz
    canfam4 : /panfs/roc/groups/0/fried255/fried255/working/pipeline/CanFam4/20210524/VEP/joint_genotype.canfam4.20210524.vep.vcf.gz
common_vars : 
    canfam3 : /panfs/roc/groups/0/fried255/fried255/working/pipeline/20210512/VEP/CommonVars/joint_genotype.canfam3.vep.af_nonmajor.vcf.gz
    canfam4 : /panfs/roc/groups/0/fried255/fried255/working/pipeline/CanFam4/20210524/VEP/CommonVars/joint_genotype.canfam4.vep.af_nonmajor.vcf.gz
common_vars_tbi : 
    canfam3 : /panfs/roc/groups/0/fried255/fried255/working/pipeline/20210512/VEP/CommonVars/joint_genotype.canfam3.vep.af_nonmajor.vcf.gz.tbi
    canfam4 : /panfs/roc/groups/0/fried255/fried255/working/pipeline/CanFam4/20210524/VEP/CommonVars/joint_genotype.canfam4.vep.af_nonmajor.vcf.gz.tbi

# REFERENCE FILES
ref_fasta :
    canfam3 : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/refdata/canFam3/canFam3.fa 
    canfam4 : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/refdata/CanFam4/canFam4.fa
ref_dict :
    canfam3 : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/refdata/canFam3/canFam3.dict
    canfam4 : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/refdata/CanFam4/canFam4.dict 
ref_gtf :
    canfam3 : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/refdata/CanFam4/canFam4_genes_ncbi.gtf.gz
    canfam4 : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/refdata/CanFam4/canFam4_genes_ncbi.gtf.gz

# RESOURCE FILES
dbsnp_indels_vcf :
    canfam3 : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/refdata/canFam3/dbsnp146.indel.vcf
    canfam4 : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/refdata/CanFam4/canFam4.recoded.dbsnp.151.indels.sorted.fixed.header.chr.vcf
dbsnp_snp_vcf :
    canfam3 : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/refdata/canFam3/dbsnp146.snp.vcf
    canfam4 : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/refdata/CanFam4/canFam4.recoded.dbsnp.151.snps.sorted.fixed.header.chr.vcf
broad_snp_vcf :    
    canfam3 : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/refdata/canFam3/final.broad.snps.vcf
    canfam4 : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/refdata/CanFam4/canFam4.final.broad.snps.sorted.fixed.header.chr.vcf
axelsson_snp_vcf :    
    canfam3 : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/refdata/canFam3/final.axelsson.snps.vcf
    canfam4 : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/refdata/CanFam4/canFam4.final.axelsson.snps.sorted.fixed.header.chr.vcf
illumina_snp_vcf :    
    canfam3 : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/refdata/canFam3/illumina.snps.vcf
    canfam4 : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/refdata/CanFam4/canFam4.illumina.snps.sorted.fixed.header.chr.vcf

# COMMON RANDOM PARAMS
excess_het_threshold : 54.69
indel_recalibration_tranche_values : ["100.0", "99.95", "99.9", "99.5", "99.0", "97.0", "96.0", "95.0", "94.0", "93.5", "93.0", "92.0", "91.0", "90.0"]
indel_recalibration_annotation_values : ["FS", "ReadPosRankSum", "MQRankSum", "QD", "SOR", "DP"]
snp_recalibration_tranche_values : ["100.0", "99.95", "99.9", "99.8", "99.6", "99.5", "99.4", "99.3", "99.0", "98.0", "97.0", "90.0" ]
snp_recalibration_annotation_values : ["QD", "MQRankSum", "ReadPosRankSum", "FS", "MQ", "SOR", "DP"]
snp_filter_level : 99.7
indel_filter_level : 99.7
