# INPUT AND SECONDARY 
units   : input.tsv
species : dog
ref     : canfam3
bucket  : wags
alias   : s3

# SINGULARITY IMAGE
sif : /path/to/wags.sif

# SORTSAM TEMP DIR
sort_tmp : /path/to/proc/dir

# LEFT ALIGN BAM
left_align : false

# BQSR INTERVAL PARAMS
contig_n_size : 50
scatter_size : 50

# REFERENCE FILES
ref_dict  : canFam3.dict 
ref_fasta : /home/refgen/dog/canfam3/canFam3.fa

# RESOURCE FILES FOR BQSR (OPTIONAL)
known_sites :
    dbsnp_indels_vcf       : /home/refgen/dog/canfam3/resources/dbsnp146.indel.vcf
    dbsnp_snp_vcf          : /home/refgen/dog/canfam3/resources/dbsnp146.snp.vcf
    broad_snp_vcf          : /home/refgen/dog/canfam3/resources/final.broad.snps.vcf
    axelsson_snp_vcf       : /home/refgen/dog/canfam3/resources/final.axelsson.snps.vcf
