# INPUT AND SECONDARY 
units   : input.tsv
species : dog
ref     : canfam4
bucket  : wags
alias   : s3
profile : slurm

# SINGULARITY IMAGE
sif : /path/to/wags.sif

# SORTSAM TEMP DIR
sort_tmp : /path/to/proc/dir

# LEFT ALIGN BAM
left_align : false

# BQSR INTERVAL PARAMS
contig_n_size : 50
scatter_size : 50

# REFERENCE FILES
ref_dict  : canFam4.dict 
ref_fasta : /home/refgen/dog/canfam4/canFam4.fa

# RESOURCE FILES FOR BQSR (OPTIONAL)
known_sites :
    dbsnp_indels_vcf       : /home/refgen/dog/canfam4/resources/canFam4.recoded.dbsnp.151.indels.sorted.fixed.header.chr.vcf
    dbsnp_snp_vcf          : /home/refgen/dog/canfam4/resources/canFam4.recoded.dbsnp.151.snps.sorted.fixed.header.chr.vcf
    broad_snp_vcf          : /home/refgen/dog/canfam4/resources/canFam4.final.broad.snps.sorted.fixed.header.chr.vcf
    axelsson_snp_vcf       : /home/refgen/dog/canfam4/resources/canFam4.final.axelsson.snps.sorted.fixed.header.chr.vcf
