# INPUT AND SECONDARY 
units   : input.tsv
species : species
ref     : ref
bucket  : wags
alias   : s3

# SINGULARITY IMAGE
sif : /path/to/wags.sif

# SORTSAM TEMP DIR
sort_tmp : /path/to/proc/dir

# LEFT ALIGN BAM
left_align : false

# BQSR INTERVAL PARAMS
contig_n_size : 50
scatter_size : 50

# REFERENCE FILES
ref_dict  : species.dict 
ref_fasta : /home/refgen/species/version/species.fa

# RESOURCE FILES FOR BQSR (OPTIONAL)
