# INPUT AND SECONDARY 
units   : input.tsv
species : horse
ref     : goldenPath
bucket  : wags
alias   : s3

# SINGULARITY IMAGE
sif : /path/to/WAGS/wags.sif

# SORTSAM TEMP DIR
sort_tmp : /path/to/proc/dir

# BQSR INTERVAL PARAMS
contig_n_size : 50
scatter_size : 50

# REFERENCE FILES
ref_dict  : goldenPath.Ec_build-3.0_wMSY.dict
ref_fasta : /home/refgen/horse/goldenPath/goldenPath.Ec_build-3.0_wMSY.fa

# RESOURCE FILES FOR BQSR (OPTIONAL)
resource_indels_vcf       : /home/refgen/species/version/resources/species.vcf
resource_indels_vcf_index : /home/refgen/species/version/resources/species.vcf.idx
resource_snp_vcf          : /home/refgen/species/version/resources/species.vcf
resource_snp_vcf_index    : /home/refgen/species/version/resources/species.vcf.idx
