# INPUT AND SECONDARY 
units   : input.tsv
species : horse
ref     : goldenPath
bucket  : wags
alias   : s3

# SINGULARITY IMAGE
sif : /path/to/WAGS/wags.sif

# SORTSAM TEMP DIR
sort_tmp : /path/to/proc/dir

# LEFT ALIGN BAM
left_align : false

# BQSR INTERVAL PARAMS
contig_n_size : 50
scatter_size : 50

# REFERENCE FILES
ref_dict  : goldenPath.Ec_build-3.0_wMSY.dict
ref_fasta : /home/refgen/horse/goldenPath/goldenPath.Ec_build-3.0_wMSY.fa

# RESOURCE FILES FOR BQSR (OPTIONAL)
dbsnp_indels_vcf       : /home/refgen/generic/resources/dbsnp146.indel.vcf
dbsnp_indels_vcf_index : /home/refgen/generic/resources/dbsnp146.indel.vcf.idx
dbsnp_snp_vcf          : /home/refgen/generic/resources/dbsnp146.snp.vcf
dbsnp_snp_vcf_index    : /home/refgen/generic/resources/dbsnp146.snp.vcf.idx
broad_snp_vcf          : /home/refgen/generic/resources/final.broad.snps.vcf
broad_snp_vcf_index    : /home/refgen/generic/resources/final.broad.snps.vcf.idx
axelsson_snp_vcf       : /home/refgen/generic/resources/final.axelsson.snps.vcf
axelsson_snp_vcf_index : /home/refgen/generic/resources/final.axelsson.snps.vcf.idx
