# INPUT AND SECONDARY 
units   : input.tsv
species : tiger
ref     : tiger
bucket  : wags
alias   : s3

# SINGULARITY IMAGE
sif : /path/to/wags.sif

# SORTSAM TEMP DIR
sort_tmp : /path/to/proc/dir

# LEFT ALIGN BAM
left_align : false

# BQSR INTERVAL PARAMS
contig_n_size : 50
scatter_size : 18

# REFERENCE FILES
ref_dict  : Tiger_final.dict
ref_fasta : /home/refgen/tiger/tiger/Tiger_final.fasta

# RESOURCE FILES FOR BQSR (OPTIONAL)
