units : input.tsv
ref : canfam3
primary : /panfs/roc/groups/0/fried255/fried255/working
hc_intervals : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/intervals/scattered_intervals_80/

# TOOLS
gatk : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/tools/gatk-4.2.0.0/gatk
gatk3 : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/tools/GenomeAnalysisTK.jar
fastqc : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/tools/FastQC/fastqc
picard : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/tools/picard.jar
bwa : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/tools/bwa-0.7.17/bwa
samtools : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/tools/samtools-1.9/samtools

# REFERENCE FILES
ref_fasta : /panfs/roc/groups/0/fried255/cull0084/projects/gatk4_pipeline/refdata/canFam3/canFam3.fa
ref_fasta_index : /panfs/roc/groups/0/fried255/cull0084/projects/gatk4_pipeline/refdata/canFam3/canFam3.fa.fai
ref_dict : /panfs/roc/groups/0/fried255/cull0084/projects/gatk4_pipeline/refdata/canFam3/canFam3.dict

# RESOURCE FILES
dbsnp_indels_vcf : /panfs/roc/groups/0/fried255/cull0084/projects/gatk4_pipeline/refdata/canFam3/dbsnp146.indel.vcf
dbsnp_indels_vcf_index : /panfs/roc/groups/0/fried255/cull0084/projects/gatk4_pipeline/refdata/canFam3/dbsnp146.indel.vcf.idx
dbsnp_snp_vcf : /panfs/roc/groups/0/fried255/cull0084/projects/gatk4_pipeline/refdata/canFam3/dbsnp146.snp.vcf
dbsnp_snp_vcf_index : /panfs/roc/groups/0/fried255/cull0084/projects/gatk4_pipeline/refdata/canFam3/dbsnp146.snp.vcf.idx
broad_snp_vcf : /panfs/roc/groups/0/fried255/cull0084/projects/gatk4_pipeline/refdata/canFam3/final.broad.snps.vcf
broad_snp_vcf_index : /panfs/roc/groups/0/fried255/cull0084/projects/gatk4_pipeline/refdata/canFam3/final.broad.snps.vcf.idx
axelsson_snp_vcf : /panfs/roc/groups/0/fried255/cull0084/projects/gatk4_pipeline/refdata/canFam3/final.axelsson.snps.vcf
axelsson_snp_vcf_index : /panfs/roc/groups/0/fried255/cull0084/projects/gatk4_pipeline/refdata/canFam3/final.axelsson.snps.vcf.idx

# NEEDED???
illumina_snp_vcf : /panfs/roc/groups/0/fried255/cull0084/projects/gatk4_pipeline/refdata/canFam3/illumina.snps.vcf
illumina_snp_vcf_index : /panfs/roc/groups/0/fried255/cull0084/projects/gatk4_pipeline/refdata/canFam3/illumina.snps.vcf.idx
