# INPUT AND SECONDARY 
units  : input.tsv
ref    : canfam3
bucket : wags
alias  : s3

# SINGULARITY IMAGE
sif : /path/to/WAGS/wags.sif

# SORTSAM TEMP DIR
sort_tmp : /path/to/proc/dir

# BQSR INTERVAL PARAMS
contig_n_size : 50
scatter_size : 50

# REFERENCE FILES
ref_dict  : canFam3.dict 
ref_fasta : /home/refgen/dog/canfam3/canFam3.fa

# BQSR
bqsr : true

# RESOURCE FILES FOR BQSR (OPTIONAL)
dbsnp_indels_vcf       : /home/refgen/dog/canfam3/resources/dbsnp146.indel.vcf
dbsnp_indels_vcf_index : /home/refgen/dog/canfam3/resources/dbsnp146.indel.vcf.idx
dbsnp_snp_vcf          : /home/refgen/dog/canfam3/resources/dbsnp146.snp.vcf
dbsnp_snp_vcf_index    : /home/refgen/dog/canfam3/resources/dbsnp146.snp.vcf.idx
broad_snp_vcf          : /home/refgen/dog/canfam3/resources/final.broad.snps.vcf
broad_snp_vcf_index    : /home/refgen/dog/canfam3/resources/final.broad.snps.vcf.idx
axelsson_snp_vcf       : /home/refgen/dog/canfam3/resources/final.axelsson.snps.vcf
axelsson_snp_vcf_index : /home/refgen/dog/canfam3/resources/final.axelsson.snps.vcf.idx

