
current_dogids : dogid_20220326.list
bucket         : friedlab
alias          : s3Fried
ref            : canfam3
date           : 20220401

# SINGULARITY IMAGE
sif : /home/fried255/cull0084/.sif/wags.sif

# CONDA ENV
conda_envs :
    qc : bcftools

# DB IMPORT
num_intervals : 243
batch_size    : 50

# REFERENCE FILES
ref_fasta : /home/refgen/dog/canfam3/canFam3.fa
ref_dict  : /home/refgen/dog/canfam3/canFam3.dict
ref_gtf   : /home/refgen/dog/canfam3/Canis_lupus_familiaris.CanFam3.1.103.gtf.gz

# TMP DIRS
tmp_dir :
    sites_only_gather_vcf : /scratch.global/friedlab_JOINT_CF3/sort_gather

# RULE-SPECIFIC PARTITIONS
partitions :
    phasing : "amdsmall,amdlarge,amd512,ram256g"

# RECAL
indel_recalibration_tranche_values    : ["100.0", "99.95", "99.9", "99.5", "99.0", "97.0", "96.0", "95.0", "94.0", "93.5", "93.0", "92.0", "91.0", "90.0"]
indel_recalibration_annotation_values : ["FS", "ReadPosRankSum", "MQRankSum", "QD", "SOR", "DP"]
snp_recalibration_tranche_values      : ["100.0", "99.95", "99.9", "99.8", "99.6", "99.5", "99.4", "99.3", "99.0", "98.0", "97.0", "90.0" ]
snp_recalibration_annotation_values   : ["QD", "MQRankSum", "ReadPosRankSum", "FS", "MQ", "SOR", "DP"]

indel_filter_level : 99.7
snp_filter_level   : 99.7

# RESOURCE FILES (FROM CONTAINER)
dbsnp_indels_vcf : /home/refgen/dog/canfam3/resources/dbsnp146.indel.vcf
dbsnp_snp_vcf    : /home/refgen/dog/canfam3/resources/dbsnp146.snp.vcf
broad_snp_vcf    : /home/refgen/dog/canfam3/resources/final.broad.snps.vcf
axelsson_snp_vcf : /home/refgen/dog/canfam3/resources/final.axelsson.snps.vcf
illumina_snp_vcf : /home/refgen/dog/canfam3/resources/illumina.snps.vcf

