date : 20210601
minio_name : s3Fried
ref : canfam4
conda_vep : vep103
gatk : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/tools/gatk-4.2.0.0/gatk
picard : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/tools/picard.jar
batch_size : 50
db_intervals : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/GoDawgs/CanFam4/Intervals
eval_interval_list : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/refdata/CanFam4/Intervals/acgt.N50.interval_list

# GVCF DIR FOR JOINT GENOTYPING
gvcf_dir : /scratch.global/friedlab_cf4GVCF/results

# REFERENCE FILES
ref_fasta : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/refdata/CanFam4/canFam4.fa
ref_fasta_index : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/refdata/CanFam4/canFam4.fa.fai
ref_dict : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/refdata/CanFam4/canFam4.dict 
ref_gtf : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/refdata/CanFam4/canFam4_genes_ncbi.gtf.gz

# RANDOM PARAMS
excess_het_threshold : 54.69

# RECAL
indel_recalibration_tranche_values : ["100.0", "99.95", "99.9", "99.5", "99.0", "97.0", "96.0", "95.0", "94.0", "93.5", "93.0", "92.0", "91.0", "90.0"]
indel_recalibration_annotation_values : ["FS", "ReadPosRankSum", "MQRankSum", "QD", "SOR", "DP"]
snp_recalibration_tranche_values : ["100.0", "99.95", "99.9", "99.8", "99.6", "99.5", "99.4", "99.3", "99.0", "98.0", "97.0", "90.0" ]
snp_recalibration_annotation_values : ["QD", "MQRankSum", "ReadPosRankSum", "FS", "MQ", "SOR", "DP"]
snp_filter_level : 99.7
indel_filter_level : 99.7

# RESOURCE FILES
dbsnp_indels_vcf : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/refdata/CanFam4/canFam4.recoded.dbsnp.151.indels.sorted.fixed.header.chr.vcf
dbsnp_indels_vcf_index : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/refdata/CanFam4/canFam4.recoded.dbsnp.151.indels.sorted.fixed.header.chr.vcf.idx
dbsnp_snp_vcf : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/refdata/CanFam4/canFam4.recoded.dbsnp.151.snps.sorted.fixed.header.chr.vcf
dbsnp_snp_vcf_index : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/refdata/CanFam4/canFam4.recoded.dbsnp.151.snps.sorted.fixed.header.chr.vcf.idx
broad_snp_vcf : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/refdata/CanFam4/canFam4.final.broad.snps.sorted.fixed.header.chr.vcf
broad_snp_vcf_index : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/refdata/CanFam4/canFam4.final.broad.snps.sorted.fixed.header.chr.vcf.idx
axelsson_snp_vcf : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/refdata/CanFam4/canFam4.final.axelsson.snps.sorted.fixed.header.chr.vcf
axelsson_snp_vcf_index : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/refdata/CanFam4/canFam4.final.axelsson.snps.sorted.fixed.header.chr.vcf.idx
illumina_snp_vcf : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/refdata/CanFam4/canFam4.illumina.snps.sorted.fixed.header.chr.vcf
illumina_snp_vcf_index : /panfs/roc/groups/0/fried255/shared/gatk4_workflow/refdata/CanFam4/canFam4.illumina.snps.sorted.fixed.header.chr.vcf.idx

# AF FREQ
var_to_table_dir : /panfs/roc/groups/0/fried255/fried255/working/all_dogs


